version: '3'
services:
  jenkins-ansible:
    container_name: jenkins-ansible
    image: jenkins-ansible
    build:
      context: jenkins-ansible/
    ports:
      - "8000:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7/
